name: Run Python Algorithm

on:
  schedule:
    - cron: "*/5 * * * *"  # Exécuter toutes les 5 minutes
  workflow_dispatch:  # Permet de lancer manuellement
  push:
    branches:
      - main  # Exécuter à chaque push sur la branche main

jobs:
  run-algorithm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: python collect.py

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add perturbations.json timetables.json
          git commit -m "Update data files [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${PAT}@github.com/agitfirat/MoveOn.git
